package GUI;

import javax.swing.*;

public class MediaDataApp extends JFrame {


    /**
     * Creates new form MainGUI
     */
    public MediaDataApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanelHome1 = new JPanel();
        jLabel3 = new JLabel();
        jPanelEingeben2 = new JPanel();
        jLabel2 = new JLabel();
        jPanelAnzeigen3 = new JPanel();
        jLabel1 = new JLabel();
        jPanelLoeschen4 = new JPanel();
        jLabel4 = new JLabel();
        jPanelAenderung5 = new JPanel();
        jLabel5 = new JLabel();
        jPanelPersistenz6 = new JPanel();
        jLabel6 = new JLabel();

        jMenuBar = new JMenuBar();

        jMenu = new JMenu();
        jMenuItemHome01 = new JMenuItem();
        jMenuItemEingeben02 = new JMenuItem();
        jMenuItemAnzeigen03 = new JMenuItem();
        jMenuItemLoeschen04 = new JMenuItem();
        jMenuItemAenderung05 = new JMenuItem();
        jMenuItemPerssitenz06 = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanelHome1.setName("jPanelHome1"); // NOI18N

        jLabel3.setText("This is Home ");
        jLabel3.setName("jLabel3"); // NOI18N

        GroupLayout jPanelHome1Layout = new GroupLayout(jPanelHome1);
        jPanelHome1.setLayout(jPanelHome1Layout);
        jPanelHome1Layout.setHorizontalGroup(
                jPanelHome1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHome1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel3)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelHome1Layout.setVerticalGroup(
                jPanelHome1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHome1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel3)
                                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanelEingeben2.setName("jPanelEingeben2"); // NOI18N

        jLabel2.setText("This is Eingeben 2");
        jLabel2.setName("jLabel2"); // NOI18N

        GroupLayout jPanelEingeben2Layout = new GroupLayout(jPanelEingeben2);
        jPanelEingeben2.setLayout(jPanelEingeben2Layout);
        jPanelEingeben2Layout.setHorizontalGroup(
                jPanelEingeben2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEingeben2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel2)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelEingeben2Layout.setVerticalGroup(
                jPanelEingeben2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEingeben2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2)
                                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanelAnzeigen3.setName("jPanelAnzeigen3"); // NOI18N

        jLabel1.setText("This is Anzeigen 3");
        jLabel1.setName("jLabel1"); // NOI18N

        GroupLayout jPanelAnzeigen3Layout = new GroupLayout(jPanelAnzeigen3);
        jPanelAnzeigen3.setLayout(jPanelAnzeigen3Layout);
        jPanelAnzeigen3Layout.setHorizontalGroup(
                jPanelAnzeigen3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAnzeigen3Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelAnzeigen3Layout.setVerticalGroup(
                jPanelAnzeigen3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAnzeigen3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel1)
                                .addContainerGap(164, Short.MAX_VALUE))
        );


        jPanelLoeschen4.setName("jPanelLoeschen4"); // NOI18N

        jLabel4.setText("This is Loeschen 4");
        jLabel4.setName("jLabel4"); // NOI18N

        GroupLayout jPanelLoeschen4Layout = new GroupLayout(jPanelLoeschen4);
        jPanelLoeschen4.setLayout(jPanelLoeschen4Layout);
        jPanelLoeschen4Layout.setHorizontalGroup(
                jPanelLoeschen4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLoeschen4Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel4)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelLoeschen4Layout.setVerticalGroup(
                jPanelLoeschen4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLoeschen4Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel4)
                                .addContainerGap(164, Short.MAX_VALUE))
        );


        jPanelAenderung5.setName("jPanelAenderung5"); // NOI18N

        jLabel5.setText("This is Aenderung 5");
        jLabel5.setName("jLabel5"); // NOI18N

        GroupLayout jPanelAenderung5Layout = new GroupLayout(jPanelAenderung5);
        jPanelAenderung5.setLayout(jPanelAenderung5Layout);
        jPanelAenderung5Layout.setHorizontalGroup(
                jPanelAenderung5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAenderung5Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel5)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelAenderung5Layout.setVerticalGroup(
                jPanelAenderung5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAenderung5Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel5)
                                .addContainerGap(164, Short.MAX_VALUE))
        );


        jPanelPersistenz6.setName("jPanelPersistenz6"); // NOI18N

        jLabel6.setText("This is Persistenz 6");
        jLabel6.setName("jLabel6"); // NOI18N

        GroupLayout jPanelPersistenz6Layout = new GroupLayout(jPanelPersistenz6);
        jPanelPersistenz6.setLayout(jPanelPersistenz6Layout);
        jPanelPersistenz6Layout.setHorizontalGroup(
                jPanelPersistenz6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPersistenz6Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel6)
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelPersistenz6Layout.setVerticalGroup(
                jPanelPersistenz6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPersistenz6Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel6)
                                .addContainerGap(164, Short.MAX_VALUE))
        );

        jMenuBar.setName("jMenuBar1"); // NOI18N

        jMenu.setText("Menu");
        jMenu.setName("jMenu"); // NOI18N

        jMenuItemHome01.setText("Home");
        jMenuItemHome01.setName("jMenuItemHome01"); // NOI18N
        jMenuItemHome01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHome1ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemHome01);

        jMenuItemEingeben02.setText("Eingeben");
        jMenuItemEingeben02.setName("jMenuItemWEigeben02"); // NOI18N
        jMenuItemEingeben02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEingeben2ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemEingeben02);

        jMenuItemAnzeigen03.setText("Anzeigen");
        jMenuItemAnzeigen03.setName("jMenuItemAnzeigen03"); // NOI18N
        jMenuItemAnzeigen03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnzeigen3ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemAnzeigen03);

        jMenuItemLoeschen04.setText("Loeschen");
        jMenuItemLoeschen04.setName("jMenuItemLoeschen04"); // NOI18N
        jMenuItemLoeschen04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoeschen4ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemLoeschen04);

        jMenuItemAenderung05.setText("Aenderung");
        jMenuItemAenderung05.setName("jMenuItemAenderng05"); // NOI18N
        jMenuItemAenderung05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAenderung5ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemAenderung05);

        jMenuItemPerssitenz06.setText("Persistenz");
        jMenuItemPerssitenz06.setName("jMenuItemPersistenz06"); // NOI18N
        jMenuItemPerssitenz06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPersistenz6ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemPerssitenz06);





        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelHome1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelEingeben2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelAnzeigen3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelLoeschen4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelAenderung5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelPersistenz6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelHome1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelEingeben2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelAnzeigen3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelLoeschen4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelAenderung5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelPersistenz6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jMenuItemHome1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(true);
        jPanelEingeben2.setVisible(false);
        jPanelLoeschen4.setVisible(false);
        jPanelAenderung5.setVisible(false);
        jPanelPersistenz6.setVisible(false);
    }

    private void jMenuItemEingeben2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(false);
        jPanelEingeben2.setVisible(true);
        jPanelAnzeigen3.setVisible(false);
        jPanelLoeschen4.setVisible(false);
        jPanelAenderung5.setVisible(false);
        jPanelPersistenz6.setVisible(false);

    }

    private void jMenuItemAnzeigen3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(false);
        jPanelEingeben2.setVisible(false);
        jPanelAnzeigen3.setVisible(true);
        jPanelLoeschen4.setVisible(false);
        jPanelAenderung5.setVisible(false);
        jPanelPersistenz6.setVisible(false);
    }

    private void jMenuItemLoeschen4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(false);
        jPanelEingeben2.setVisible(false);
        jPanelAnzeigen3.setVisible(false);
        jPanelLoeschen4.setVisible(true);
        jPanelAenderung5.setVisible(false);
        jPanelPersistenz6.setVisible(false);
    }

    private void jMenuItemAenderung5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(false);
        jPanelEingeben2.setVisible(false);
        jPanelAnzeigen3.setVisible(false);
        jPanelLoeschen4.setVisible(false);
        jPanelAenderung5.setVisible(true);
        jPanelPersistenz6.setVisible(false);
    }

    private void jMenuItemPersistenz6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jPanelHome1.setVisible(false);
        jPanelEingeben2.setVisible(false);
        jPanelAnzeigen3.setVisible(false);
        jPanelLoeschen4.setVisible(false);
        jPanelAenderung5.setVisible(false);
        jPanelPersistenz6.setVisible(true);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaDataApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaDataApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaDataApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaDataApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaDataApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;

    private JMenu jMenu;
    private JMenuBar jMenuBar;

    private JMenuItem jMenuItemHome01;
    private JMenuItem jMenuItemEingeben02;
    private JMenuItem jMenuItemAnzeigen03;
    private JMenuItem jMenuItemLoeschen04;
    private JMenuItem jMenuItemAenderung05;
    private JMenuItem jMenuItemPerssitenz06;
    private JPanel jPanelHome1;
    private JPanel jPanelEingeben2;
    private JPanel jPanelAnzeigen3;
    private JPanel jPanelLoeschen4;
    private JPanel jPanelAenderung5;
    private JPanel jPanelPersistenz6;


    // End of variables declaration
}
